### ISSUE TITLE
How can I get page.path in Gitbook 2.0

### ISSUE THREAD

**Issue by saturngod** [GitbookIO/plugin#14]
I am using page.path in "page:after" for loading file.

At version 2.0 , we cannot use "page:after". So, I try to change with block. However, I have no idea , how to get full file path without page.path .

**Comment by SamyPesse** [comment]
You can use `this.ctx.file.path` (markdown page can acces it using `{{ page.path }}`)

**Comment by SamyPesse** [comment]
The path `this.ctx.file.path` is relative to the book, to get an absolute path use:

```
path.resolve(this.book.root, this.ctx.file.path)
```
